// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcarwjemzpwcodhboxvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYXJ3amVtenB3Y29kaGJveHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1Njg0NjYsImV4cCI6MjA5MTE0NDQ2Nn0.Zjn3_RKfcZDK8H5aqd80nSXajkSUNRSkBXiLqJyYSc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});